<?php

namespace AppBundle\Repository;

/**
 * LifeStyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LifeStyleRepository extends \Doctrine\ORM\EntityRepository
{
}
