<?php

namespace AppBundle\Repository;

/**
 * PersonalProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalProgramRepository extends \Doctrine\ORM\EntityRepository
{
}
