<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'knp_menu.menu_provider.lazy' shared service.

include_once $this->targetDirs[3].'/vendor/knplabs/knp-menu/src/Knp/Menu/Provider/LazyProvider.php';

return $this->services['knp_menu.menu_provider.lazy'] = new \Knp\Menu\Provider\LazyProvider(array('sonata_admin_sidebar' => function () {
    return ${($_ = isset($this->services['sonata.admin.sidebar_menu']) ? $this->services['sonata.admin.sidebar_menu'] : $this->load('getSonata_Admin_SidebarMenuService.php')) && false ?: '_'};
}));
