<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.admin.filter_persister.session' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Filter/Persister/FilterPersisterInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Filter/Persister/SessionFilterPersister.php';

return $this->services['sonata.admin.filter_persister.session'] = new \Sonata\AdminBundle\Filter\Persister\SessionFilterPersister(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load('getSessionService.php')) && false ?: '_'});
