<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.block.cache.handler.noop' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/block-bundle/src/Cache/NoopHttpCacheHandler.php';

return $this->services['sonata.block.cache.handler.noop'] = new \Sonata\BlockBundle\Cache\NoopHttpCacheHandler();
