<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.core.model.adapter.chain' shared service.

@trigger_error('The "sonata.core.model.adapter.chain" service is deprecated since 3.x and will be removed in 4.0.', E_USER_DEPRECATED);

$this->services['sonata.core.model.adapter.chain'] = $instance = new \Sonata\CoreBundle\Model\Adapter\AdapterChain();

$instance->addAdapter(${($_ = isset($this->services['sonata.core.model.adapter.doctrine_orm']) ? $this->services['sonata.core.model.adapter.doctrine_orm'] : $this->load('getSonata_Core_Model_Adapter_DoctrineOrmService.php')) && false ?: '_'});

return $instance;
