<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.core.twig.status_runtime' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Twig/Extension/StatusRuntime.php';

$this->services['sonata.core.twig.status_runtime'] = $instance = new \Sonata\CoreBundle\Twig\Extension\StatusRuntime();

$instance->addStatusService(${($_ = isset($this->services['sonata.core.flashmessage.manager']) ? $this->services['sonata.core.flashmessage.manager'] : $this->load('getSonata_Core_Flashmessage_ManagerService.php')) && false ?: '_'});

return $instance;
