<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.core.model.adapter.doctrine_orm' shared service.

@trigger_error('The "sonata.core.model.adapter.doctrine_orm" service is deprecated since 3.x and will be removed in 4.0.', E_USER_DEPRECATED);

return $this->services['sonata.core.model.adapter.doctrine_orm'] = new \Sonata\CoreBundle\Model\Adapter\DoctrineORMAdapter(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
